version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=     
    volumes:
      - payment-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  payment-pgdata: